from mcp.server.fastmcp import FastMCP
from db_connector import connect_db, close_conn

mcp = FastMCP('qna-mekari-mcp')

@mcp.tool()
def read_ktp(query: str = "SELECT * FROM transactions LIMIT 5") -> list:
    """Read data from the "transactions" table using a SQL SELECT query. 
    The table contains legitimate and fraud credit card transactions from the duration 1st Jan 2019 - 31st Dec 2020. 
    It covers credit cards of 1000 customers doing transactions with a pool of 800 merchants. 

    Args:
        query (str): SQL SELECT query. 
        Defaults to "SELECT * FROM transactions".
            Examples:
            - "SELECT document_name, name, nik, birth_place FROM transactions"
            - "SELECT document_name, name, nik, birth_place FROM transactions WHERE name = 'John Doe'"
            - "SELECT document_name, name, nik, birth_place FROM transactions ORDER BY name DESC"

    Schema:
        - id_upload: Text field => The identifier of uploaded documents.
        - document_name: Text field => The document name generated by the system.
        - name: Text field => The cardholder's name.
        - nik: Text field => The cardholder's ID number.
        - birth_place: Text field => The cardholder's birth place.
        - birth_date: Date field => The cardholder's birth date.
        - address: Text field => The cardholder's address.
        - gender: Text field => The cardholder's gender.
        - blood_type: Text field => The cardholder's Blood type.
        - marital_status: Text field => The cardholder's marital status. KAWIN is Married, BELUM KAWIN is not married, CERAI is divorced.
        - religion: Text field => The cardholder's religion.
        - work_occupation: Text field => The cardholder's occupation.
        - nationality: Text field => The cardholder's nationality. WNI is Indonesian, WNA is non-Indonesian.

    
    Returns:
        list: List of tuples containing the query results.
    
    """
    conn, cursor = connect_db()
    try:
        cursor.execute(query)
        return cursor.fetchall()
    except mysql.connector.Error as e:
        print(f"Error reading data: {e}")
        return []
    finally:
        close_conn(conn)

if __name__ == "__main__":
    print("Starting server... ")
    mcp.settings.host = "127.0.0.1"
    mcp.settings.port = 4000
    mcp.run(transport="sse")

